# Generated by Django 4.1.1 on 2022-11-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_otpuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpuser',
            name='secret_otp',
            field=models.CharField(max_length=16),
        ),
    ]
