# Generated by Django 4.1.1 on 2022-10-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='account',
            new_name='account_id',
        ),
    ]
