# Generated by Django 4.1.1 on 2022-11-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0008_remove_account_account_number_account_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=541545416, max_length=30),
            preserve_default=False,
        ),
    ]
