# Generated by Django 4.1.1 on 2022-11-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0009_account_account_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='customer_fk_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_number',
            new_name='number',
        ),
    ]
