# Generated by Django 4.1.1 on 2023-01-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0010_rename_customer_fk_id_account_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotentBroker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idempotent_key', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
