# Generated by Django 4.1.1 on 2022-11-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0007_alter_ledger_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
        migrations.AddField(
            model_name='account',
            name='account_name',
            field=models.CharField(default='Name', max_length=30),
            preserve_default=False,
        ),
    ]
