# Generated by Django 4.1.1 on 2022-11-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0010_rename_customer_fk_id_account_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='secret_otp',
            field=models.CharField(default='T8NASA3C10', max_length=30),
            preserve_default=False,
        ),
    ]
