# Generated by Django 4.1.1 on 2022-11-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0011_customer_secret_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='secret_otp',
        ),
    ]
